### ISSUE TITLE
Php_win64.tar.xz idk need help

### ISSUE THREAD

**Issue by GrimDevs** [iTXTech/PHP-Genisys#11]
I fought tar was for Linux operating system

**Comment by GrimDevs** [comment]
please install Visual C++ 2015 Redistributable Package first. I thought it was only for win 8.1 an win 7 sp1 I have win Home premiere

**Comment by AndreTheGamer** [comment]
@GrimDevs You can extract a **.tar.xz** using ``tar -xf FileName.tar.xz```
