### ISSUE TITLE
php7

### ISSUE THREAD

**Issue by astersx** [iTXTech/PHP-Genisys#12]
Wich php7 i should choose?

**Comment by ishitatsuyuki** [comment]
Idiot. Learn about architectures and operating systems.

**Comment by astersx** [comment]
Suck my dick asshole, and fuck genisys,  tomorow i will remove,  fuck you,  and i even screenshoot your comment, all i did was to ask a question fucking retard,  no life sucker!

**Comment by ishitatsuyuki** [comment]
This is issue tracker, not support center. If you don't know what is architecture and OS, GitHub is not a place for you.
