### ISSUE TITLE
PHP7 for Linux x64?

### ISSUE THREAD

**Issue by andris155** [iTXTech/PHP-Genisys#18]

**Comment by ishitatsuyuki** [comment]
Use Docker. Can't you read README?

**Comment by andris155** [comment]
I use Multicraft. My friend don't know ssh, and docker. Multicraft using very easy.

**Comment by ishitatsuyuki** [comment]
Use Multicraft at your risk. I will recommend an alternative, pufferpanel, which can configured to use Docker.
