### ISSUE TITLE
Can't run PHP7

### ISSUE THREAD

**Issue by PocketKiller** [iTXTech/PHP-Genisys#3]
Hello, I am using PHP7 x64 (My windows is 64x) it isn't working, I've tried x32 also, but same.
I am ALWAYS getting this : 
```
/usr/bin/php/php.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory
bin\php\php.exe: Exit 127
```
Thanks.

**Comment by PeratX** [comment]
Please read README.md carefully!!!!
